import Link from "next/link";
import { Noto_Sans } from "next/font/google";

import { ThemeProvider } from "@components/theme-provider";
import Header from "@components/header";

import "./globals.css";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Web Engineering by Raul Glogovețan",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-zinc-50 dark:bg-zinc-900 text-zinc-900 dark:text-slate-50 ${notoSans.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div>
            <Header />
            <main className="prose dark:prose-invert max-w-none">{children}</main>
            <footer className="bg-white dark:bg-black mt-20">
              <div className="max-w-3xl mx-auto py-40 px-4">
                <div className="flex items-center justify-between">
                  <nav className="ml-auto text-sm font-medium space-x-6">
                    <Link href="/">Home</Link>
                  </nav>
                </div>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
