import { Noto_Sans } from "next/font/google";

import { ThemeProvider } from "@components/theme-provider";
import Header from "@components/header";
import Footer from "@components/footer";

import "./globals.css";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Web Engineering by Raul Glogovețan",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-zinc-50 dark:bg-zinc-900 text-zinc-900 dark:text-slate-50 ${notoSans.className}`}
      >
        <ThemeProvider attribute="class" enableSystem>
          <div>
            <Header />
            <main className="prose dark:prose-invert max-w-none">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
